module.exports = {
  // env: {
  //   MICRO_CMS_API_URL: process.env.MICRO_CMS_API_URL,
  //   MICRO_CMS_API_KEY: process.env.MICRO_CMS_API_KEY,
  //   AMPLIFY_COGNITO_IDENTITYPOOL_ID: process.env.AMPLIFY_COGNITO_IDENTITYPOOL_ID,
  //   AMPLIFY_COGNITO_REGION: process.env.AMPLIFY_COGNITO_REGION,
  //   AMPLIFY_COGNITO_USERPOOL_ID: process.env.AMPLIFY_COGNITO_USERPOOL_ID,
  //   AMPLIFY_COGNITO_USERPOOL_WEBCLIENT_ID: process.env.AMPLIFY_COGNITO_USERPOOL_WEBCLIENT_ID
  // },
  reactStrictMode: true,
  output: 'standalone'
};
